/**
 * Tests for the Markdown export function and settings filtering.
 */

import { describe, it, expect } from "vitest";
import type { AnalysisResult, CheckResult } from "../src/content/seo-checks";

// ---------------------------------------------------------------------------
// Types matching popup.ts
// ---------------------------------------------------------------------------

interface UserSettings {
  enabledChecks: Record<string, boolean>;
}

// Inline the formatMarkdownReport function to test it without DOM deps
function formatMarkdownReport(
  result: AnalysisResult,
  settings: UserSettings,
): string {
  const enabledChecks = result.checks.filter(
    (c) => settings.enabledChecks[c.id] !== false,
  );

  let md = `# SEO Analysis Report\n\n`;
  md += `**URL:** ${result.url}\n`;
  md += `**Score:** ${result.overallScore}/100\n`;
  md += `**Date:** ${new Date(result.timestamp).toLocaleString()}\n\n`;
  md += `---\n\n`;

  for (const check of enabledChecks) {
    const icon =
      check.status === "pass"
        ? "\u2705"
        : check.status === "warning"
          ? "\u26a0\ufe0f"
          : "\u274c";
    md += `## ${icon} ${check.name} (${check.score}/100)\n\n`;

    if (check.issues.length === 0) {
      md += `All checks passed.\n\n`;
    } else {
      for (const issue of check.issues) {
        md += `- **[${issue.severity.toUpperCase()}]** ${issue.message}\n`;
        md += `  - *Fix:* ${issue.recommendation}\n`;
      }
      md += `\n`;
    }
  }

  md += `---\n*Generated by SEOPilot Lite*\n`;
  return md;
}

// ---------------------------------------------------------------------------
// Helper: create a mock AnalysisResult
// ---------------------------------------------------------------------------

function createMockResult(overrides?: Partial<AnalysisResult>): AnalysisResult {
  return {
    url: "https://example.com/page",
    title: "Example Page",
    overallScore: 75,
    scoreColor: "yellow",
    timestamp: 1710000000000,
    checks: [
      {
        id: "meta-title",
        name: "Meta Title",
        status: "pass",
        score: 100,
        weight: 20,
        issues: [],
        details: { title: "Example Page Title", length: 18 },
      },
      {
        id: "meta-description",
        name: "Meta Description",
        status: "fail",
        score: 0,
        weight: 20,
        issues: [
          {
            ruleId: "meta-desc-missing",
            severity: "critical",
            message: "Meta description is missing.",
            recommendation: "Add a meta description.",
          },
        ],
        details: { description: "", length: 0 },
      },
      {
        id: "headings",
        name: "Heading Structure",
        status: "pass",
        score: 100,
        weight: 15,
        issues: [],
        details: { counts: { h1: 1, h2: 2 }, h1Text: "Main" },
      },
      {
        id: "image-alt",
        name: "Image Alt Text",
        status: "warning",
        score: 50,
        weight: 15,
        issues: [
          {
            ruleId: "image-alt-missing",
            severity: "warning",
            message: "2 of 4 images missing alt text.",
            recommendation: "Add descriptive alt text.",
          },
        ],
        details: { totalImages: 4, withAlt: 2, withoutAlt: 2, lowQualityAlt: 0 },
      },
      {
        id: "links",
        name: "Link Analysis",
        status: "pass",
        score: 100,
        weight: 15,
        issues: [],
        details: { totalLinks: 5, internalLinks: 3, externalLinks: 2, nofollowLinks: 0, emptyLinks: 0 },
      },
      {
        id: "social-meta",
        name: "OG / Twitter Card",
        status: "warning",
        score: 56,
        weight: 15,
        issues: [
          {
            ruleId: "twitter-card-incomplete",
            severity: "info",
            message: "Twitter Card tags incomplete.",
            recommendation: "Add missing Twitter Card tags.",
          },
        ],
        details: { ogFieldsPresent: 3, twFieldsPresent: 2 },
      },
    ],
    ...overrides,
  };
}

// ===========================================================================
// Tests
// ===========================================================================

describe("formatMarkdownReport", () => {
  it("should include URL, score, and date", () => {
    const result = createMockResult();
    const settings: UserSettings = {
      enabledChecks: {
        "meta-title": true,
        "meta-description": true,
        headings: true,
        "image-alt": true,
        links: true,
        "social-meta": true,
      },
    };

    const md = formatMarkdownReport(result, settings);

    expect(md).toContain("**URL:** https://example.com/page");
    expect(md).toContain("**Score:** 75/100");
    expect(md).toContain("# SEO Analysis Report");
    expect(md).toContain("*Generated by SEOPilot Lite*");
  });

  it("should include all 6 checks when all enabled", () => {
    const result = createMockResult();
    const settings: UserSettings = {
      enabledChecks: {
        "meta-title": true,
        "meta-description": true,
        headings: true,
        "image-alt": true,
        links: true,
        "social-meta": true,
      },
    };

    const md = formatMarkdownReport(result, settings);

    expect(md).toContain("Meta Title");
    expect(md).toContain("Meta Description");
    expect(md).toContain("Heading Structure");
    expect(md).toContain("Image Alt Text");
    expect(md).toContain("Link Analysis");
    expect(md).toContain("OG / Twitter Card");
  });

  it("should filter out disabled checks", () => {
    const result = createMockResult();
    const settings: UserSettings = {
      enabledChecks: {
        "meta-title": true,
        "meta-description": true,
        headings: false,
        "image-alt": false,
        links: true,
        "social-meta": false,
      },
    };

    const md = formatMarkdownReport(result, settings);

    expect(md).toContain("Meta Title");
    expect(md).toContain("Meta Description");
    expect(md).toContain("Link Analysis");
    expect(md).not.toContain("Heading Structure");
    expect(md).not.toContain("Image Alt Text");
    expect(md).not.toContain("OG / Twitter Card");
  });

  it("should show pass icon for passing checks", () => {
    const result = createMockResult();
    const settings: UserSettings = {
      enabledChecks: { "meta-title": true },
    };

    const md = formatMarkdownReport(result, settings);

    // Passing check gets green checkmark
    expect(md).toContain("\u2705 Meta Title (100/100)");
    expect(md).toContain("All checks passed.");
  });

  it("should show fail icon and issues for failing checks", () => {
    const result = createMockResult();
    const settings: UserSettings = {
      enabledChecks: { "meta-description": true },
    };

    const md = formatMarkdownReport(result, settings);

    expect(md).toContain("\u274c Meta Description (0/100)");
    expect(md).toContain("**[CRITICAL]** Meta description is missing.");
    expect(md).toContain("*Fix:* Add a meta description.");
  });

  it("should show warning icon for warning checks", () => {
    const result = createMockResult();
    const settings: UserSettings = {
      enabledChecks: { "image-alt": true },
    };

    const md = formatMarkdownReport(result, settings);

    expect(md).toContain("\u26a0\ufe0f Image Alt Text (50/100)");
    expect(md).toContain("**[WARNING]** 2 of 4 images missing alt text.");
  });

  it("should handle empty checks list (all disabled)", () => {
    const result = createMockResult();
    const settings: UserSettings = {
      enabledChecks: {
        "meta-title": false,
        "meta-description": false,
        headings: false,
        "image-alt": false,
        links: false,
        "social-meta": false,
      },
    };

    const md = formatMarkdownReport(result, settings);

    expect(md).toContain("# SEO Analysis Report");
    expect(md).toContain("*Generated by SEOPilot Lite*");
    // Should have no check headers
    expect(md).not.toContain("## ");
    // Wait, the header uses "# " and the separator uses "---"
    // Actually "## " would match check headers. Let's check more specifically.
    expect(md.split("##").length).toBe(1); // No H2 headers
  });
});

describe("Settings filtering", () => {
  it("should recalculate score when checks are disabled", () => {
    const result = createMockResult();
    const allEnabled: UserSettings = {
      enabledChecks: {
        "meta-title": true,
        "meta-description": true,
        headings: true,
        "image-alt": true,
        links: true,
        "social-meta": true,
      },
    };

    // With only passing checks enabled, score should be higher
    const passingOnly: UserSettings = {
      enabledChecks: {
        "meta-title": true,
        "meta-description": false,
        headings: true,
        "image-alt": false,
        links: true,
        "social-meta": false,
      },
    };

    const enabledChecks = result.checks.filter(
      (c) => passingOnly.enabledChecks[c.id] !== false,
    );

    let totalWeight = 0;
    let weightedScore = 0;
    for (const check of enabledChecks) {
      totalWeight += check.weight;
      weightedScore += check.weight * check.score;
    }
    const filteredScore =
      totalWeight > 0 ? Math.round(weightedScore / totalWeight) : 0;

    // All 3 enabled checks (meta-title, headings, links) have score 100
    expect(filteredScore).toBe(100);
  });

  it("should default to enabled when check not in settings", () => {
    const result = createMockResult();
    const partialSettings: UserSettings = {
      enabledChecks: {
        "meta-title": true,
        // Other checks not specified — should default to enabled
      },
    };

    const enabledChecks = result.checks.filter(
      (c) => partialSettings.enabledChecks[c.id] !== false,
    );

    // All checks should be included since none are explicitly false
    expect(enabledChecks.length).toBe(6);
  });
});
